

# Enviroment Varibles
export PROJECT=artmart-city
export PROJECT_FRONTEND=artmart-city-frontend
export DEPLOY_ROOT=/web
export HOME=$DEPLOY_ROOT
export DEPLOY_DIR=$DEPLOY_ROOT/$PROJECT
export WEB_USER=www-data


# Frontend 
export DOMAIN=staging.artmart.city
export BACKEND_APP_NAME=amc-api
export WEB_APP_NAME=amc-web-app
export APP_DIR=$HOME/$PROJECT_FRONTEND
export BACKEND_DIR=$APP_DIR/$BACKEND_APP_NAME
export WEB_APP_DIR=$APP_DIR/$WEB_APP_NAME
export MEDIA_DIR=$APP_DIR/media/
export STATIC_DIR=$DEPLOY_DIR/static/


# Backend 
export UWSGI_APPS_ENABLED_DIR=/etc/uwsgi/apps-enabled
export UWSGI_APPS_AVAIL_DIR=/etc/uwsgi/apps-available
export UWSGI_RUN_DIR=/run/uwsgi/app/$PROJECT
export SUPERVISOR_DIR=/etc/supervisor
export SUPERVISOR_CONF_DIR=/etc/supervisor/conf.d
export UWSGI_SOCKET_PATH=0.0.0.0:8000
export UWSGI_WORKERS=1
export UWSGI_MAX_REQUESTS=5000
export UWSGI_BUFFER_SIZE=8192

export BACKEND_REPO=ssh://jenkins@calderon.solutions:29418/art/artmart-city.git 

